### ISSUE TITLE
[Question] How to make it work with IE11?

### ISSUE THREAD

**Issue by bhupesh** [Genivia/SJOT#3]
I have SJOT implemented and working fully on chrome. I have a requirement to make same work on IE11 too. When I load SJOT in IE11 it gives error at `class` keyword. Can you please advice? Thanks.

**Comment by genivia-inc** [comment]
I've updated sjot.js to replace all ES6 features and tested it against IE11. The update will be released once the code reviews and regression testing are complete. For a sneak peak: our interactive demo at [https://www.genivia.com/get-sjot.html](https://www.genivia.com/get-sjot.html) uses the updated version to validate JSON and check SJOT schemas. We may update the SJOT schema converters also, but not very soon. These still use ES6 features.

**Comment by genivia-inc** [comment]
Fixed in 1.3.16.
